### ISSUE TITLE
Spam Console

### ISSUE THREAD

**Issue by deanle8** [Monoto72/GlobalStats#1]
When I click on mined blocks, the console shows the following:
![image](https://user-images.githubusercontent.com/77945073/179190294-250643b6-0ce9-4ca7-94ae-3ce0d3756c3c.png)

**Comment by Monoto72** [comment]
Hey @deanle8 ! Thank you for notifying me this, I honestly forgot while preparing the Spigot page. This has been fixed in the build just pushed.

[GlobalStats-1.0](https://github.com/Monoto72/GlobalStats/commit/fc84f4ec73c96d05fa991a27bafb66419341fd79)
