### ISSUE TITLE
GUI ERROR

### ISSUE THREAD

**Issue by deanle8** [Monoto72/GlobalStats#2]
https://pastes.dev/636qIpBBy7
Error when I click on Killing category

**Comment by Monoto72** [comment]
Hey @deanle8. This has now been resolved. I forgot to remove the stack trace I was using for debugging. Anyways, thank you for using the correct channels, I appreciate it.

Resolved: [Commit](https://github.com/Monoto72/GlobalStats/commit/d4d53c1e22936c9873c8370c2a7683a948611e02)
Published: [Spigot](https://www.spigotmc.org/resources/globalstats-offline-support-gui-based.103379/)
