### ISSUE TITLE
Placeholder API Support?

### ISSUE THREAD

**Issue by devbaraus** [Monoto72/GlobalStats#3]
Is it possible to add placeholders so we can use to display stat on chat and scoreboards?

**Comment by Monoto72** [comment]
Yes it's possible. For now I will add it for all of the global stats, and each of the players top overall stats. I'm planning on reworking it all soon to allow for many more statistics to be included i.e. death, time played, etc.

For example,
- %globalstats_mined%
- %globalstats_mined_{<player>}%

**Comment by Monoto72** [comment]
Sorry for the wait. All has been done. 

Link to the recent is here, along with the correct placeholders. [GlobalStats-1.5](https://www.spigotmc.org/resources/globalstats-offline-support-gui-based.103379/update?update=475123)

**Comment by devbaraus** [comment]
> Yes it's possible. For now I will add it for all of the global stats, and each of the players top overall stats. I'm planning on reworking it all soon to allow for many more statistics to be included i.e. death, time played, etc.
> 
> For example,
> 
> * %globalstats_mined%
> * %globalstats_mined_{}%

It will me quite usefull to me, I'm creating some ranks that will depend on this kind of information
